#ifndef CENTERWIDGETONE_GLOBAL_H
#define CENTERWIDGETONE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CENTERWIDGETONE_LIBRARY)
#  define CENTERWIDGETONESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CENTERWIDGETONESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CENTERWIDGETONE_GLOBAL_H
