#ifndef CENTERWIDGETTWO_GLOBAL_H
#define CENTERWIDGETTWO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CENTERWIDGETTWO_LIBRARY)
#  define CENTERWIDGETTWOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CENTERWIDGETTWOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CENTERWIDGETTWO_GLOBAL_H
